site_name: GoCRUD
site_url: https://ckoliber.dev/gocrud
copyright: Copyright &copy; 2025 KoLiBer.
repo_name: ckoliber/gocrud
repo_url: https://github.com/ckoliber/gocrud
edit_uri: edit/main/docs/
theme:
    name: "material"
    palette: {}
markdown_extensions:
    - admonition
    - pymdownx.keys
    - pymdownx.emoji
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.snippets
    - pymdownx.tasklist
    - pymdownx.inlinehilite
    - pymdownx.highlight:
          linenums: true
nav:
    - README: README.md
    - Introduction: introduction.md
    - Getting Started: getting-started.md
    - Configuration: configuration.md
    - CRUD Operations: crud-operations.md
    - CRUD Hooks: crud-hooks.md
    - Advanced Topics: advanced-topics.md
    - FAQ: FAQ.md
