site_name: GoCRUD Documents
theme:
    name: "material"
    palette: {}
markdown_extensions:
    - admonition
    - pymdownx.keys
    - pymdownx.emoji
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.snippets
    - pymdownx.tasklist
    - pymdownx.inlinehilite
    - pymdownx.highlight:
          linenums: true
nav:
    - README: README.md
    - Introduction: introduction.md
    - Getting Started: getting-started.md
    - Configuration: configuration.md
    - CRUD Operations: crud-operations.md
    - CRUD Hooks: crud-hooks.md
    - Advanced Topics: advanced-topics.md
    - FAQ: FAQ.md
